# -------- CUSTOMIZE ABILITY --------

# Automatically repair all damaged tools in player inventory
# true: auto-repair false: default repair
auto-repair: false

# The removed experience when the mending ability is used
# You'd better use ratio instead
# default: 20
expValue: 20

# A multiplier for the gained durability
# default: 2.0
ratio: 2.0

# -------- AUTO-REPAIR --------

# auto-repair must be set to true to use these functionalities!

# The delay (in ticks) between each tool's repair
# 20 ticks = 1 second
# default: 40
delay: 40

# True if auto-repair should repair the full inventory for every [delay] ticks or false if it should only repair one tool for every [delay] ticks
# default: true
repairFullInventory: true

# -------- SOUNDS --------

# Should play a sound if the power of mending is used.
# true: played / false: not played
playSound: true

# The volume of the sound, 1 is default
soundVolume: 1

# The speed of the sound, 1 is default, smaller than 1 is slower
soundPitch: 1

# -------- EFFECT --------
# Enable or disable the effect
playEffect: true

# The color used in the effect (RGB, each value need to be between 0 and 255)
# default (in the order of color): 144, 238, 144
color:
  red: 144
  green: 238
  blue: 144

# Please, do not touch!
version: 3