name: BetterMending
main: io.github.paulem.btm.BTM
version: 2.4.1
website: paulem79.github.io
author: Paulem
description: A small quality of life tweak to the Mending enchantment
api-version: 1.13

permissions:
  btm.use:
    description: Allows to use the mending ability
    default: true