# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defense
# against bad commits.

name: 🔨 Build
on:
  workflow_call:
  push:
    branches:
      - master
    tags:
      - dev
  pull_request:

jobs:
  build:
    name: 🔨 Build gradle project
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: ✅ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🪄 Cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./.gradle/loom-cache
          key: ${{ runner.os }}-gradle0-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle0-

      - name: ✅ Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: 🛠️ Setup jdk 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          java-package: jdk

      - name: 🆙 Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: 🔨 Build project
        run: ./gradlew build

      - name: ✅ Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/